name: Publish from develop
env:
  ARTIFACTORY: urmilag.jfrog.io/docker-local/
  CONTAINER_IMAGE: $ARTIFACTORY/sample-app
on:
  push: 
    branches: [develop,dockerpush]
jobs:
  publish-docker-image:
    env:
      ARTIFACTORY_BUCKET: docker-local
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and tag docker image
      run: |
        docker build . --file ./scripts/build/Dockerfile \
        -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::8}
    - name: Setup Jfrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        VERSION: 1.39.3
      env:
        JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_CONFIG }} 
    - name: Ping to jfrog cli
      run: |
        jfrog rt ping
    - name: Publish docker image
      run: jfrog rt dp ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::8} ${{ env.ARTIFACTORY_BUCKET }}service/test   
