name: Publish from master
env:
  ARTIFACTORY: urmilag.jfrog.io/docker-qa
  ARTIFACTORY_BUCKET: docker-qa
  CONTAINER_IMAGE: $ARTIFACTORY/sample-app-master
on:
  push: 
    branches: [master]
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and tag docker image
      run: |
        docker build . --file ./scripts/build/Dockerfile -t ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::8}
    - name: Setup Jfrog CLI
      uses: jfrog/setup-jfrog-cli@v1
      with:
        VERSION: 1.39.3
      env:
        JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_CONFIG }} 
    - name: Ping to jfrog cli
      run: |
        jfrog rt ping
    - name: Publish docker image
      run: jfrog rt dp ${{ env.CONTAINER_IMAGE }}:${GITHUB_SHA::8} $ARTIFACTORY_BUCKET
